


expart: 
	cd ../testenv
	nextpnr-ecp5 --85k --json "../debug/withnets_sorted.json" \
		--lpf ../examples/collatz.lpf \
		--textcfg collatzer.config \
		--pre-pack ../nextpnr/constrainer.py \
		# --pre-pack ../debug/pre_pack.py