/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.4.3. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module merger
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input [8:0] vo
    , input [8:0] ve

      // Outputs
    , output wire [7:0] res
    );
  // testenv/builds/merger/Synth_merger.hs:(13,1)-(14,63)
  wire [7:0] c$ds_case_alt;
  // testenv/builds/merger/Synth_merger.hs:(13,1)-(14,63)
  wire [7:0] c$ds_app_arg;
  // testenv/builds/merger/Synth_merger.hs:5:1-6
  wire [8:0] vo_0;
  // testenv/builds/merger/Synth_merger.hs:5:1-6
  wire [8:0] ve_0;
  // testenv/builds/merger/Synth_merger.hs:5:1-6
  wire [7:0] v;
  // testenv/builds/merger/Synth_merger.hs:5:1-6
  wire [7:0] v_0;
  wire [17:0] eta;

  assign eta = {vo,   ve};

  assign c$ds_case_alt = ve_0[8:8] ? v_0 : 8'd0;

  assign c$ds_app_arg = vo_0[8:8] ? v : c$ds_case_alt;

  assign vo_0 = eta[17:9];

  assign ve_0 = eta[8:0];

  assign v = vo_0[7:0];

  assign v_0 = ve_0[7:0];

  assign res = c$ds_app_arg;


endmodule

