/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.4.3. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module router
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input [15:0] val

      // Outputs
    , output wire [16:0] odd
    , output wire [16:0] even
    );
  wire [33:0] result_0;
  wire [16:0] c$app_arg;
  wire [16:0] c$app_arg_0;
  wire  c$case_scrut;
  wire [15:0] c$bv;
  wire [33:0] result;

  assign result = result_0;

  assign result_0 = {c$app_arg_0,   c$app_arg};

  assign c$app_arg = c$case_scrut ? {1'b1,val} : {1'b0,16'bxxxxxxxxxxxxxxxx};

  assign c$app_arg_0 = c$case_scrut ? {1'b0,16'bxxxxxxxxxxxxxxxx} : {1'b1,val};

  assign c$bv = (val);

  assign c$case_scrut = (c$bv[(64'sd0)]) == (1'b1);

  assign odd = result[33:17];

  assign even = result[16:0];


endmodule

