/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.4.6. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module system
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input [16:0] setting

      // Outputs
    , output wire [15:0] result
    );


  system_system system_system_result
    ( .result (result)
    , .c$bindCsr (clk)
    , .c$bindCsr_0 (rst)
    , .c$bindCsr_1 (en)
    , .eta (setting) );


endmodule

