/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.4.6. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module system_mergerM
    ( // Inputs
      input  c$bindCsr // clock
    , input  c$bindCsr_0 // reset
    , input  c$bindCsr_1 // enable
    , input [33:0] eta

      // Outputs
    , output wire [15:0] result
    );
  // Clash.hs:(62,1)-(63,63)
  wire [15:0] c$ds_case_alt;
  // Clash.hs:(62,1)-(63,63)
  wire [15:0] c$ds_app_arg;
  // Clash.hs:30:1-6
  wire [16:0] vo;
  // Clash.hs:30:1-6
  wire [16:0] ve;
  // Clash.hs:30:1-6
  wire [15:0] v;
  // Clash.hs:30:1-6
  wire [15:0] v_0;

  assign c$ds_case_alt = ve[16:16] ? v_0 : 16'd0;

  assign c$ds_app_arg = vo[16:16] ? v : c$ds_case_alt;

  assign vo = eta[33:17];

  assign ve = eta[16:0];

  assign v = vo[15:0];

  assign v_0 = ve[15:0];

  assign result = c$ds_app_arg;


endmodule

