/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.4.6. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module system_system
    ( // Inputs
      input  c$bindCsr // clock
    , input  c$bindCsr_0 // reset
    , input  c$bindCsr_1 // enable
    , input [16:0] eta

      // Outputs
    , output wire [15:0] result
    );
  wire [15:0] c$result_rec;
  wire [15:0] result_0;
  wire [32:0] c$result_rec_fun_arg;

  assign c$result_rec_fun_arg = {result_0,
                                 eta};

  system_controlM system_controlM_c$result_rec
    ( .result (c$result_rec)
    , .c$controller_result_value_bindCsr (c$bindCsr)
    , .c$controller_result_value_bindCsr_0 (c$bindCsr_0)
    , .c$controller_result_value_bindCsr_1 (c$bindCsr_1)
    , .i1 (c$result_rec_fun_arg) );

  system_collatzer system_collatzer_result_0
    ( .result (result_0)
    , .c$controller_result_value_bindCsr (c$bindCsr)
    , .c$controller_result_value_bindCsr_0 (c$bindCsr_0)
    , .c$controller_result_value_bindCsr_1 (c$bindCsr_1)
    , .eta (c$result_rec) );

  assign result = c$result_rec;


endmodule

