/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.4.6. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module system_collatzer
    ( // Inputs
      input  c$controller_result_value_bindCsr // clock
    , input  c$controller_result_value_bindCsr_0 // reset
    , input  c$controller_result_value_bindCsr_1 // enable
    , input [15:0] eta

      // Outputs
    , output wire [15:0] result
    );
  wire [33:0] result_0;
  wire [16:0] result_1;
  wire [16:0] result_2;
  wire [16:0] result_fun_arg;
  wire [16:0] result_fun_arg_0;
  wire [33:0] result_fun_arg_1;

  system_routerM system_routerM_result_0
    ( .result (result_0)
    , .c$ds_bindCsr (c$controller_result_value_bindCsr)
    , .c$ds_bindCsr_0 (c$controller_result_value_bindCsr_0)
    , .c$ds_bindCsr_1 (c$controller_result_value_bindCsr_1)
    , .eta (eta) );

  assign result_fun_arg = result_0[33:17];

  system_onOddM system_onOddM_result_1
    ( .result (result_1)
    , .c$bindCsr (c$controller_result_value_bindCsr)
    , .c$bindCsr_0 (c$controller_result_value_bindCsr_0)
    , .c$bindCsr_1 (c$controller_result_value_bindCsr_1)
    , .eta (result_fun_arg) );

  assign result_fun_arg_0 = result_0[16:0];

  system_onEvenM system_onEvenM_result_2
    ( .result (result_2)
    , .c$bindCsr (c$controller_result_value_bindCsr)
    , .c$bindCsr_0 (c$controller_result_value_bindCsr_0)
    , .c$bindCsr_1 (c$controller_result_value_bindCsr_1)
    , .eta (result_fun_arg_0) );

  assign result_fun_arg_1 = {result_1,
                             result_2};

  system_mergerM system_mergerM_result
    ( .result (result)
    , .c$bindCsr (c$controller_result_value_bindCsr)
    , .c$bindCsr_0 (c$controller_result_value_bindCsr_0)
    , .c$bindCsr_1 (c$controller_result_value_bindCsr_1)
    , .eta (result_fun_arg_1) );


endmodule

