/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.4.6. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module system_onEvenM
    ( // Inputs
      input  c$bindCsr // clock
    , input  c$bindCsr_0 // reset
    , input  c$bindCsr_1 // enable
    , input [16:0] eta

      // Outputs
    , output wire [16:0] result
    );
  // Clash.hs:(70,1)-(71,56)
  wire [16:0] c$ds_app_arg;
  // Clash.hs:46:1-6
  wire [15:0] v;

  assign c$ds_app_arg = eta[16:16] ? {1'b1,v >> (64'sd1)} : {1'b0,16'bxxxxxxxxxxxxxxxx};

  assign v = eta[15:0];

  assign result = c$ds_app_arg;


endmodule

