/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.4.3. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module onEven
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input [8:0] value

      // Outputs
    , output wire [8:0] res
    );
  // testenv/builds/onEven/Synth_onEven.hs:(11,1)-(12,56)
  wire [8:0] c$ds_app_arg;
  // testenv/builds/onEven/Synth_onEven.hs:5:1-6
  wire [7:0] v;

  assign c$ds_app_arg = value[8:8] ? {1'b1,v >> (64'sd1)} : {1'b0,8'bxxxxxxxx};

  assign v = value[7:0];

  assign res = c$ds_app_arg;


endmodule

